_core:
  default_config_hash: GL7ygb-sUJwtEtFI_8Z3Qd8mBJpr2h5lTL6DIOQKs98
smtp_host: smtp.gmail.com
smtp_hostbackup: ''
smtp_port: 587
smtp_protocol: tls
smtp_username: dion.zeneli@dropsolid.com
smtp_password: 'katx wlyb enqu oibb'
smtp_hide_password: false
smtp_authentication_type: basic_auth
smtp_fromname: Dominique
smtp_always_replyto: false
smtp_keepalive: false
smtp_debug: 2
smtp_debug_log: true
phpmailer_smtp_test: ''
smtp_ssl_verify_peer: true
smtp_ssl_verify_peer_name: true
smtp_ssl_allow_self_signed: false
smtp_envelope_sender_option: default
smtp_envelope_sender: ''
smtp_ehlo_host: ''
smtp_timeout: 30
